### ISSUE TITLE
Render Datamations in Rmarkdown?

### ISSUE THREAD

**Issue by jhofman** [microsoft/datamations#117]
@sharlagelfand, let's see if it "just works" to render a datamation in an html Rmarkdown document?

**Comment by sharlagelfand** [comment]
Yes, just works! 🎉  all good in [an Rmd with html_document](https://github.com/microsoft/datamations/blob/test-rmd/sandbox/test_rmd.Rmd) output (as we would expect to use, since it's HTML based).

The [HTML file](https://github.com/microsoft/datamations/blob/test-rmd/sandbox/test_rmd.html) renders fine locally for me, but for some reason not in a [github preview of the file](https://htmlpreview.github.io/?https://raw.githubusercontent.com/microsoft/datamations/test-rmd/sandbox/test_rmd.html) - I'm not sure what the difference is! But it looks like @giorgi-ghviniashvili's [test file](https://htmlpreview.github.io/?https://github.com/microsoft/datamations/blob/main/inst/htmlwidgets/test/index.html) doesn't render in the github preview either, even though it works locally!

**Comment by giorgi-ghviniashvili** [comment]
Hi @sharlagelfand , bunch of errors in the console, I don't know why:

![image](https://user-images.githubusercontent.com/6615532/142487508-72902ec5-5388-4f43-9b8e-a3af5afc67b7.png)


Here d3 is missing and has problems with in operation, possible need polyfill? 

![image](https://user-images.githubusercontent.com/6615532/142487572-cda08b77-6b05-47c4-82b9-b99645eaa4d0.png)

**Comment by jhofman** [comment]
Amazing that it "just works"!

Seems like the github preview is a problem w/ htmlpreview.github.io.

I tried rawcdn.githack.com, an alternative, and it's working fine there. Hooray!

https://rawcdn.githack.com/microsoft/datamations/c33abbdd8654df1d3d6ccaaf84bdd444188068f6/sandbox/test_rmd.html

**Comment by sharlagelfand** [comment]
oh perfect! Crisis averted. I'll close this now, feel free to reopen if there's anything else!
