### ISSUE TITLE
Take a pass on documentation and tidying things up

### ISSUE THREAD

**Issue by jhofman** [microsoft/datamations#130]
Let's check on documentation for users of the package and documentation for developers as @sharlagelfand is wrapping things up.

**Comment by jhofman** [comment]
Would be nice to have a section that explains our conventions, e.g., one-variable grouping is x-axis, two-variable is x-axis + row facet, etc.

This could go in the readme or in a vignette.

**Comment by jhofman** [comment]
@sharlagelfand, can you add some about the automated tests / integration and also documentation generation

**Comment by jhofman** [comment]
reminder: let's discuss how the handoff of updates from the rendering side get incorporated into the R package / shiny app. wasn't obvious to me from the documentation.

**Comment by jhofman** [comment]
what's up w/ the `R/dmta_*` functions? looks like those are for tibble-style but not sanddance style, maybe?

**Comment by sharlagelfand** [comment]
@giorgi-ghviniashvili is editing the JS files directly in the `htmlwidgets` folder so any JS changes are picked up automatically, and the package is built any time someone installs / updates it - nothing needs to be done on the actions end because the package isn't built on GitHub, just when it's installed.

All the `R/dmta_*` functions are leftover from the tibble-style, yup! Do we want to go ahead and just remove those?

**Comment by sharlagelfand** [comment]
@jhofman here's the details on package dev / testing / renv etc: https://github.com/microsoft/datamations/tree/main/R#package-development

Individual functions are still documented there, just lower down.

Conventions (re grouping etc) are here: https://microsoft.github.io/datamations/articles/details.html with lots of examples here: https://microsoft.github.io/datamations/articles/Examples.html Since these are legitimate HTML files they can be demo'd directly (rather than GIFs which you're at the mercy of!) so could be a decent sub in while the Shiny issues are in flux.
