### ISSUE TITLE
Can't have multiple datamations widgets on the same page

### ISSUE THREAD

**Issue by sharlagelfand** [microsoft/datamations#133]
Looks like the way datamations widgets are created / controlled is not actually independent, making it not possible right now to properly have multiple on one page (e.g. to show multiple examples). Will demo in our meeting.

**Comment by sharlagelfand** [comment]
@giorgi-ghviniashvili [here](https://raw.githubusercontent.com/microsoft/datamations/documentation/docs/articles/Examples.html) is the HTML file with multiple widgets for debugging - thank you!

**Comment by giorgi-ghviniashvili** [comment]
hi @sharlagelfand , that's definitely because `window.app` is used everywhere:

![image](https://user-images.githubusercontent.com/6615532/146510347-092ec16d-76e0-4ac1-a5cc-71a90b29d6ce.png)

Instead, it should be either window.app1, window.app2 or list of apps: [app1, app2, app3] and then access it as `window.apps[index]`.. Can you make that list?

**Comment by sharlagelfand** [comment]
@giorgi-ghviniashvili each app is created independently [here](https://github.com/microsoft/datamations/blob/main/inst/htmlwidgets/datamationSandDance.js#L10) so I'm not able to make a list of apps - I will try to used the element ID to make each app unique though (e.g. `window.htmlwidget-5a23eaf6aa3b92eb698b` or something). Thanks!

**Comment by sharlagelfand** [comment]
Solved by making each app name unique with the ID (e.g. `window.apphtmlwidget5a23eaf6aa3b92eb698b`) - all good!
