### ISSUE TITLE
Gracefully handle unsupported operations

### ISSUE THREAD

**Issue by jhofman** [microsoft/datamations#149]
Related to #31, let's figure out how to handle unsupported or plot-based no-op verbs like arrange and select

**Comment by jhofman** [comment]
Right now we throw an error and say that you've used an unsupported function.

Next time let's talk about whether we could support "no-op" verbs in some consistent way.

**Comment by willdebras** [comment]
I have updated this handling to be a bit more graceful. Instead of erroring on all non supported verbs, we just warn and skip on no-ops:

```
"small_salary %>%
  select(Degree, Salary) %>%
  group_by(Degree) %>%
  arrange(desc(Salary)) %>%
  summarize(mean = mean(Salary))" %>%
  datamation_sanddance()
```

This pipeline results in console warnings like this:

Warning messages:
1: In .f(.x[[i]], ...) :
  Pipeline step for select discarded as a non-visualized function.
2: In .f(.x[[i]], ...) :
  Pipeline step for arrange discarded as a non-visualized function.
  
  @jhofman 
  
  1. Do you have specific language you want here?
  2. Are there other verbs besides arrange or select you can think of that we should just skip instead of erroring on?

**Comment by jhofman** [comment]
looks good.

let's double check that the pipeline runs as intended (e.g., if the `mean(Salary)` was a `first(Salary)` we'd get a different result with and without and arrange).

**Comment by willdebras** [comment]
Confirmed the pipeline runs as intended with arrange, just doesn't visualize it.
