### ISSUE TITLE
Some question about R

### ISSUE THREAD

**Issue by giorgi-ghviniashvili** [microsoft/datamations#34]
Hi @jhofman  and @sharlagelfand , I will ask some questions about R here and if you have some time, please answer. 

Some of them might be very dumb , sorry about that ..

**Comment by giorgi-ghviniashvili** [comment]
* what is %>% ?
* where is the entry point of datamations 
* how to run whole R script file into Shiny app without ctrl + enter for each line?

**Comment by jhofman** [comment]
> * what is %>% ?

that is a great question. you can think of it like a unix pipe that passes the output of one command the input of the next. (specifically it passes the output as the first argument of the next command, but you can override that with the dot operator if you like.) more [here](https://r4ds.had.co.nz/transform.html#combining-multiple-operations-with-the-pipe).

> * where is the entry point of datamations

i'll leave that one for @sharlagelfand.

> * how to run whole R script file into Shiny app without ctrl + enter for each line?

i think you're looking for cmd-shift-return, but see these [rstudio keyboard shortcuts](https://support.rstudio.com/hc/en-us/articles/200711853-Keyboard-Shortcuts)

**Comment by sharlagelfand** [comment]
> where is the entry point of datamations

not sure what you mean @giorgi-ghviniashvili, can you clarify?

**Comment by giorgi-ghviniashvili** [comment]
@jhofman  thanks, just tested 1st and 3rd 

![image](https://user-images.githubusercontent.com/6615532/116134637-314e4e80-a6e1-11eb-90b6-417be780cb5e.png)

**Comment by giorgi-ghviniashvili** [comment]
> not sure what you mean @giorgi-ghviniashvili, can you clarify?

For example, in js env, we have `package.json` and there is startup script defined in `package.json`, was looking forward something like that where the exported functions of `datamations` reside.

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand my intention is to start reading R and know where to start from..

**Comment by sharlagelfand** [comment]
hmm I think something similar (from what I just read about `package.json`) is the [`DESCRIPTION`](https://github.com/jhofman/datamations/blob/main/DESCRIPTION) file, which contains the title, license, people, dependencies, etc. The [`NAMESPACE`](https://github.com/jhofman/datamations/blob/main/NAMESPACE#L3) file contains the names of all the functions we export, on lines starting with `export`. The function definitions themselves are in the [`R/` directory](https://github.com/jhofman/datamations/tree/main/R) and any documentation is rendered into [`man/`](https://github.com/jhofman/datamations/tree/main/man). let me know if i can provide more info!

**Comment by sharlagelfand** [comment]
@giorgi-ghviniashvili If you want to understand how each of the stages is happening in datamations, I'd look at the code in my [`refactor-test` branch](https://github.com/jhofman/datamations/tree/refactor-test/R) moreso than the main branch, since it has been simplified a fair amount and focuses on generating the coordinates and vegalite specs for each stage, rather than the ggplot2 graphics and GIFs in the main branch.

For example, [`datamation_sanddance()`](https://github.com/jhofman/datamations/blob/refactor-test/R/datamation_sanddance.R) is the first R function called, and it loops through [`animate_group_by_sanddance()`](https://github.com/jhofman/datamations/blob/refactor-test/R/animate_group_by_sanddance.R) and [`animate_summarize_mean_sanddance()`](https://github.com/jhofman/datamations/blob/refactor-test/R/animate_summarize_mean_sanddance.R) to define the stages and specs for each of `group_by()` and `summarize()`
