### ISSUE TITLE
Multiple axis in fake faceted views

### ISSUE THREAD

**Issue by giorgi-ghviniashvili** [microsoft/datamations#39]
I got an idea to render two vega specs, one for axis and not touched by Gemini and second for fake faceted with animated by Gemini.

**Comment by giorgi-ghviniashvili** [comment]
@jhofman  Started working on this, but finding it hard to exactly match points: 

Upper ones are real ones, below ones are faked. 

![image](https://user-images.githubusercontent.com/6615532/117142621-f7580900-adc0-11eb-99a9-dae3d7692bcc.png)

**Comment by jhofman** [comment]
@giorgi-ghviniashvili looks like a pretty good start, in fact i'm not sure what looks "off" other than the lower-left panel where the blue points are outside of the axes?

**Comment by giorgi-ghviniashvili** [comment]
Points are duplicated, one point is from real faceted view, the other one is faked (a bit below). These two needs to match exactly and have only one circle, like this: 

![image](https://user-images.githubusercontent.com/6615532/117160504-35a9f400-add2-11eb-93dd-782d1862a387.png)

**Comment by giorgi-ghviniashvili** [comment]
@jhofman  made it work: 

Two vega graphs are overlaid.

Inner axes is drawn using "vega spec for axis".

Outer axes done with fake faceted spec. Notice that because we are using fake faceted view we can have facet axis on the right, which would not be possible with real faceted view because it is not supported yet. 

![image](https://user-images.githubusercontent.com/6615532/117299079-2b96fc80-ae89-11eb-9de8-2ad0b85ee388.png)

**Comment by sharlagelfand** [comment]
@giorgi-ghviniashvili this looks great! If I want to pass a title for the y-axis in the jitter/summary frames, does it make sense to just pass that through in the y encoding `title`?

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand , yes I think it will work

**Comment by sharlagelfand** [comment]
Just to keep track of here, previously the axis appeared as soon as the points moved from infogrid -> jitter

https://user-images.githubusercontent.com/15895337/117502278-4763d680-af4d-11eb-9a72-bcf449f45cd0.mov

But now it looks like they only appear when moving jitter -> summary

https://user-images.githubusercontent.com/15895337/117502298-4f237b00-af4d-11eb-8f00-16d1ef34ed8e.mov

Probably better to keep them on for longer (the first case)

**Comment by jhofman** [comment]
@giorgi-ghviniashvili as discussed yesterday, can you check and confirm that the bounding boxes of the real and fake axes line up?

**Comment by giorgi-ghviniashvili** [comment]
@jhofman yes, currently they line up correctly.

**Comment by giorgi-ghviniashvili** [comment]
As per @jhofman 's comment that points don't line up correctly:

![image](https://user-images.githubusercontent.com/6615532/118787962-5e3aef00-b8a4-11eb-9027-3ece1d4b9560.png)

@sharlagelfand  could you please do this:

![image](https://user-images.githubusercontent.com/6615532/118788061-73b01900-b8a4-11eb-8d15-bd4f6930a7f4.png)
 
Avoid using decimals, and have 1, 2, 3 in `axis.values`. Adjust padding using `scale.domain` (and always include `scale.domain`).

We will get this: 

![image](https://user-images.githubusercontent.com/6615532/118788238-a4904e00-b8a4-11eb-813a-23bbdcc1c0a9.png)

![image](https://user-images.githubusercontent.com/6615532/118788262-ac4ff280-b8a4-11eb-98bc-6af7058c26b5.png)

**Comment by sharlagelfand** [comment]
Thanks @giorgi-ghviniashvili!

I have a question about the Y domain in the jitter and summary frames - I've set the Y domain to be the range of the data as we discussed so that the summary points are in the same range as the jitter points. It all looks good in the animation but when you actually click on the last summary frame, you can see it has a different Y domain:

https://user-images.githubusercontent.com/15895337/118813453-22d8fa00-b87d-11eb-86d7-512f27b3ff9d.mov

Do you know why the domain looks like this? The actual frame itself in the [vega lite editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoMohqyaAfRrK0ARiUARcgCc4cNCACySCJjguBkoAHvZKAJ5oAJwADJQATPEAbADMKWIxMUl2AOypAL4KJmYW1rao8U6u7p4+fgFBIKGoDiCRqLEJyWkZWbkFRSCmCOZWNmgpVWRuHuh1-oGKTWFt0XGJqemZ2XkphcUjpeOoYlMztb4Ljc2t7Z0bPdv9e4PDo2VoAKxnNXOXDUsbhE1l1Nr0dgMDu9jkkfrNvP9FiEVnd1t0tn1dvshiUxuUcnCLvUkcsWsCOmiwU8sa9cR9UAAOQl-YnXFEgh4YiEvKFHcpRZkI1mA9kU0GPTGQnGHPH2GKC+YA5Fk1Zizng57Yt58+ytZzTX5Cq4ilWo8VczW0mX0uyVED684s43K24c9Eamm82UtSb26rwxUkoGq+7u6lS7XeuynP0GgOItmmt1UyU86XQ8p2b6xx1GpWk11qsOprV0452WE5w2BxOF0Mp7ml63lglV+PCl3k+sSxtWjP2JltonOgtdyk9y1em0CodO-PBs3q8NpyP0+Ly2d5oOi7sWz3pnUVPX+4fznfjvcRsvlRIKhMmusXj1X5s330O6v3zshp-Lpv9ioYw-dsRwXZMJ33VdjnibNgNPbckyLBtJwPb1kjvDtRx-c1nxXa80HiVs4LnBDHxwv8+0PeJB2IrdazHciS0otCZ1omsHwYpcmKnY4Ug3Nivywxdi17HjyhSY843g+jsK40TUPpFI7QEzCwKQiCXwAtIMNA89GPkqDxKAk8SJk4TkMg-DUBSWCTLojjZJElDDImSsVN0xDd1w-9DxSIi7PY79zI0vDXwmGiAsEtSvIosSJlYyLVL0uTnKsjIdLPTzf24hTjjESTc0CoTwMvUKALEZTEo8siUsssKTnfKrMpqpy6vK4ypNMhzgtKnzvTEWzOvsoKSu85j6TENymtIzjWs0w8xH8oaiui7KDLSiLlqi5K5rKhaEq2pKsv01L6s+fjprM0bYty8pPgKz8jpaiz5u9T5KsO6rZpeva3saz7mu+kK+vpT4OsK7bjtq17QcGiGnqB3rxuOT4poBmbHJ+kGUaW+Gvsx4Hkbuza8cBgmkbi1BPgO0mMZ6sbKaSC70au9SKdutBsgyunrpylzUCSD7adZmK+as1JuZFtbToApJwce-H6Zu-mkjhhWyaVsX6qSNHhe63n1u13H1Z5tmGY5gWSZNqWTraw8khp639bN5WrJyZm9ZGl2tYAnIHpAjWDZlw8ciFp2vdFw3ff+3MAAUYEcZ2GQZBIBqZ7JuniOwomx-F5fhePE695PU9RvpM+z3O0ByNWC4TpOU-iNPy9SLOc6J6vdcNQuG9L9PbVbyuO9QHJjbrovisZRvm4zwf28pnIrfH3um7L2elKHhfHeX4vp7XgeN-ni2GQ97v693vuW8PqvGX9zwe4v1f+4ro-+YZMOd8nkun6vtub4ZGOZ8J5qW-jPA+f9h4Mnzvfc+X897Pznv-WuMDgGilAfvF+-8u6fxAfA3+m9j5jxQSvMBmDIFL2IY-UhiDIHb0oXAy+68IGU1iIKB+DCf5MIIfzKId90DsNwYw8B3CrJRA-vQwRnDhGv1EYAnBaC8FcJkfVKI0D+GwMkdQ6+w8ojIPUagxC6CEHaJYdgiRCihFkJYUQ-RJCME0JYRQ2xVD7EmItlEOhziOFaOYRbOwmQ2EaIsVIzBABdQoIAABmSAoBwEwGgUAUA2C6AQPITQUSaBwEEOUIcShMDhBwPCNgLhlDmB0EsTAdBBDwjgvkCJEBClQASRgOANAyBYAmAEkAAB3Gw9B7DnSUMgFwABrZp+TCmeBwGwcw8SlCRJoIIap5RMAuD0BEuAsgkmlNkGQZpzRQALKyTk0IeSCnwgAI4MCQLISp6hKmkCWEgYINADDpO0LofQRgHB2FCUoQQSAmBZIAKLBBwC4TwIAIl3OqZCpQ0AdCzFAMoNgyBzBGDiN8OwlBPjhIie0Q5mTsmeEiGcyZ6Ark3LuWoGgjy8lVPhAAZR0EgFwpKQAItheklFaK0mGAZNi1RA0Yh2BSAAh2nwmSqMoDELO91bSowdmIBkeK6n5CAA) doesn't look like that:

![visualization(3)](https://user-images.githubusercontent.com/15895337/118814393-1dc87a80-b87e-11eb-9f66-e64f15bd9df8.png)

In the [specs here](https://github.com/jhofman/datamations/blob/fixes/sandbox/specs.json) you can see that the Y domain is the same for the [jitter](https://github.com/jhofman/datamations/blob/fixes/sandbox/specs.json#L723) and the [summary frame](https://github.com/jhofman/datamations/blob/fixes/sandbox/specs.json#L1371) - is there something going on with that final frame that changes its axis? Thanks!

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand good catch, fixed it. Please update shiny app with this commit.

**Comment by sharlagelfand** [comment]
Looks good, thanks @giorgi-ghviniashvili!
