### ISSUE TITLE
Add error bars to summarized frames

### ISSUE THREAD

**Issue by jhofman** [microsoft/datamations#44]
we discussed adding error bars to the summarized plots. 

@giorgi-ghviniashvili: can we do this with just one "layer" in vegalite, or do we have to hack things again? could you play with this in the vegalite editor and then see if gemini can handle it?

if it is possible (🤞), then @sharlagelfand, we'll just need to add to the vegalite spec when exporting.

**Comment by giorgi-ghviniashvili** [comment]
@jhofman [error bars](https://vega.github.io/editor/#/examples/vega-lite/layer_point_errorbar_ci) are available using layer field, which is not supported by gemini. 
[Box plots](https://vega.github.io/editor/#/examples/vega-lite/boxplot_minmax_2D_vertical) does not use layers, but does all the quantile calculations internally.

**Comment by jhofman** [comment]
could we either a) fake them in the same way you're doing with facet axes, by creating a second layer or b) try to add to gemini internally as per #49?

**Comment by giorgi-ghviniashvili** [comment]
@jhofman which one to try first? I have not started gemini code reading yet.

**Comment by jhofman** [comment]
a) seems easier if it's possible to just turn on an extra layer with the error bars

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand can you prepare specs for this for me to work with?

**Comment by sharlagelfand** [comment]
@giorgi-ghviniashvili I'm having some trouble figuring out error bars with facets - have you done this before?

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand  no , I have never done error bars with facets before. I only have this example: https://vega.github.io/vega-lite/examples/layer_point_errorbar_stdev.html

**Comment by giorgi-ghviniashvili** [comment]
Some progress: 

https://user-images.githubusercontent.com/6615532/118880230-b0126200-b902-11eb-91a5-156a8b10c9bf.mov

**Comment by sharlagelfand** [comment]
@giorgi-ghviniashvili [Here](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoMohqyaAfRrK0ARiUARcgCc4cNCACySCJjguBkoAHvZKAJ5oAJwADJQATPEAbADMKQAsMTFJdgDsqRGWLkgA7mgAHHaUUenpYjF2KeUpSVFi5QC+CiZmFta2qPFOru6ePn4BQSChqA4gkaixCclpmdl5BfNFpRXxlOVtKVliSenl8Xad3SCmCOZWNmgpw2RuHujj-oGK02Hz0XFEqkMlkcvlnltimVUM0EkkTnl4ulcvEYmJ4l0enc+o9UOkXm8xr4vlMZnMFksgatQRsIeFttDzvsom1kcl4ek7Jibr0HgMxATRh9iZMfmSIgDlsC1mDNvSoZLLrlclE7I0kiq7FFubd7v00ElBe9vCLviE-hTASsQetwYUFYs4ilGgcYmkUrkxM6dbz9ahckaiRMzb9ZhLHVLqba5QzJWl4Z6xLl0jUGj7sXyKoHhcHSRbJVSbbK6bGYVFKElyuUxHYk+cUicUum9biotmTbmxfmI4WZbT7TsyxWkylVTUPS1mziBnYYu3PqLzWH-j3rX27ZDBwd9rPneVasm7EkklPM7M5s5XkKOySu8vLZGi-3N9ClnZamJ6jWjrOxKe-XYQwgJehI5reS7kgWa40hu8qDpSYhRLkWTxFE8Qou+-64o086mnm95QdKMExg627tDEKL5LUbpalhM74sBIzGguIbiiulLQdGJYOqqlDIp6rRiOkqR5LkdH2AKjFXsxeF3pBq5EVxA6vnEQkXGsaJJIkXLXLq072IaUmgTei6hvJHGKcWymSm0MTnF6DRREcTa6b62EBkZ14sfh5lWpZz5wYy6SUCk8QIpR7Qsi5WItjO5S4Z2EHhhZUZWS+kr5HZiT7jWSYYq5GYAW2nkyYlZnJX5qUBaWvHqW0VYnORVwxfpgxziVQbgeV7GVU+sE1VUZxqp+LLVqO+UtWeFwJV1bEPr2xHcfBVSog2aLlLkaq0QVsVoIkM2mXNhFVf1pHBe+2TNIB6JNNqO2tfEEIgV5slJT1j7riR8FxLEWQssJyrbZNfpIgdrHdilfVfa+VQZMi6INGqiQTTyhW4mFYM+RVH2LdZEY5K0SJaRkTk6cD6OGc9pWzRDvWfUtMOUHkURjc6SJNOk4mDB5VOdYdtM40p6WLCtKYesJ9ZHie91TfFHVgfzBEKSd0PRINMRix6yENWJMsg8VvMK+DSuQ-TeO8Wq8INhkVaiVzRyY3J2MLULgVq0zl2nKhTlodFqO7agzqO2982cWlbv48h6TxOUboaoBZP+61oXB91of+ady18a0+7HptB4o3pZ5pKnR3K1DDPu2iKqaUeUec3ruIZKXAsu+HNU-ekcNHqhG2fvbkmGyZxu+YL7c8VUeSZJ+yHobl9uU0xfMj87YfVRPCSZLWiQtF6LL2zzS9G1j71t+v32UPUapNM0MfVs1SfF3LQ-eU7p9r5njISGkbqoo0KaqgfkXP0o4W4mzprjYWSwkgaxiKhDIYVQqFzcgMTIYDR5n0-hUCQKYaycmaDEKKQCUFoE5Og1eGdVYiz4scDWhM6j5C5tHch79KGV2oe+fILIogwKQt6RuqCnpH2HifdOKt2FLCju0XIVYLg1mIWjVBDEX6vTTsdCu5s4g5CrB6LU+5PQN3JqgwewjX4h3UWbKBqlgQ1jdEcIETDF7SWXqIixkCI5LEQpUVkDZNoXCYYfZxx835iI0VAyeyE3SZGSJRROwDcRnBYaEyxHi4jJhRBtQ4uQmhxJIXiA2pjVFl1Nu4mqewGg5E4dWE4VYub1CSW412ZSEjeK7l6FUTlDGPz9DWBp5cUkDUvn-eRj1sjZDqUBFRZVikQKaTxPYSJsiPXZLES4dShFBJESExp48tzBSEnZL0pweGzl1kYtAQk+klLmVnAm742bCS7mc7puJPxXNmbs185TOTCScsmLuG06lOOMmYtR-TSnzISGhd8LNPZ2TqYEkFRTW4fyobxHOtZAK91jgogO7R3lj3PozA4MDkTHNRMeOpBTNmgpmYSrBiw9j4OVBcY8iEUxcxgQSzBaKqgbTzs6GRGtakCINBeQp0yUVsPNnsJoGtQoHJkR6TlkyJU03AfStFexEQ8M9GhMKXdOUbKRZKjVPKJHavRDHbKBweF-lFagU43LUXsOrNnQCKYziwtQpykxNLkVmpdTKpmNRPy8IosiO65zHXApeqajBQbwmX0QptElFK3ScsRXG9VCbpVJpZNpMKaFqzPPiQMSszq80eKZZWISgE0LImVQ61olbxHmyqCzNCBaamomQYotAyFW1hI8R2toqQyWhUrLi1qm0h0DMhUcfc1ZWi-K9FzFEc6IVZ2TL42sNR6x9oDtk9sAAFGAjhtkwnKJvE46wVgXGKhHfcfFyiVndDdLSpa8nJlPeey9VYb0wJyPerUeNYS51VKOKsvzD0zr9cZM9F7zFXsA3e1ID6wMpEoJ6Z0TQ5HJg1Ou2NxpEP-uvUiW9wH0OgeFm65It9ahs1ONOs8ypf1IbBQBijQHALUcfYM6eFxLhbVfV+-t-pn7CNI8hrjdQeMgf46Rb+RxVRUR4a0aW0aVTsbI6hqjoUaPVpCl6zIscMgtE0y8gYscdMyfI3JtDBnFN7OwxzU4HSyUsb9JUWznH7OUd405sDEhQTVMSG6RGXNzi+bLrJgLCngtM1SKCSsLN4S5PE80GL3Y4vyb44lrWuigPHK87ifc2Wla5ccxh2jIXzjQdsd+LpZbsEVfklV-TNWn1JEoGiJoe8wp2WRFF4jnhpN+b04FrrNUsNHjgVpI8nIagZYDhtNr4YOtTcM6WN1qpsh1ALbglbrUqzrZXJthLUCsOZBZp+eoMdYjNbyQcM7CwLv5doz12BNjax1DOFzWIr2Kj+by0Fq7vWkxLOQjfNIAPxWbPG7FkH1XtukR67UNk5xCF5Ewg6tCQOUPcZR85r5rm8Maz+SzMTAcnIE-e2D7rIUNRVg2nAiiSEAfKKk3+uzk3LtPtyL1lMcDVQxy0pZlrix4PXkRzl5HnXUfwVmzA7HrQjxfgB6N9AsvKvy62yTioPXKzoUaEJI4xyAdZpIzzibROFcG8WFh6HaIiH1AyADyTCObdI75x9gXfFRzM2RNHT8x2zwsjp3r-nM39hpBZayxI9ro2znakPHX7Wo9+5qsFOBmLrrHn3R0AAul0EAAAzJAUA4CYDQKAKAbBdAIHkJocvNA4CCAGB1JQmBwg4GNGwFwyhzA6B+JgOgghjS8w6KXiAfeoC14wHAGgZAsBPCyEoEoNh6ASXaoIJA4QAhGFAMgFwABrTwAQXAD6YEgFwPw4CyHr0P2QZAF8zFAGXtvHfPChG77340AAjgwEgLIGPuoGPqQD8EgMEDQAYC3toLoPoEYA4HYEXkoHvkwO3gAKLBA4B37oAgCl5gET6eA-DQA6DvCgDKBsDIDmBGCqQKBVBiAl6l4LAf5f6d5ux-596eBAEgFgFqA0CQHd7j7GgADKOgt+kQSg5BJBLe1BtBzehglQ1QH4DQTQLQ9UCgNQvWciSMJwK65QLB0+1wJ+5+LePePB6AOAbA5gNeSgn+ggE+AwmALgegpeD+T+5gr+Le7+re7enev+IAlhgBwBoBdAghwhIA0BsBC+CBegcBhgKBaBIAGB2BuB+BIAhBIhmAchWRMhUAFBC+ChSAdBqAhgDBTBLB4Y7BARng0hwR-+vBYRAhEBHgOReREhe+LgDRshlBKgNBpRShKhNQdQ6hzQgk8UOhueNY+ehhxhxe0+QAA) is an example of having error bars in facets, and how it looks:

![visualization(4)](https://user-images.githubusercontent.com/15895337/118999034-ededa580-b957-11eb-9398-7fd103f31163.png)


I realized the domain isn't really an issue because it's the full domain of the data, so.... of course the error bar should fit within that 😅 

In the summary spec, we precalculate the mean (and each point has the exact same value) and then send that over to vega lite, but in order for this to work we need to send the original values themselves to be used for the error bars. So rather than switch the y values (in case that messes with the animations) I've created a new variable `y_raw` that contains the original values (that construct the error bar) and kept `y` as the mean values themselves. I'll work out creating a full set of specs for this now.

**Comment by sharlagelfand** [comment]
Ok, here are example (full) specs with an errorbar at the end for [facet](https://github.com/microsoft/datamations/blob/parse-ggplot2/sandbox/errorbar/specs_with_facet.json) and [non-facet](https://github.com/microsoft/datamations/blob/parse-ggplot2/sandbox/errorbar/specs_no_facet.json) cases.

I couldn't figure out having errorbars when there are both column and row facets - you can see [here](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoMohqyaAfRrK0ARiUARcgCc4cNCACySCJjguBkoA6mwuANaeAIJQSMpmKEoAHvZKAJ5oABwALJQADABMAJyZmQDMdkUAbKV5DiBpli5IAO5ZdpRF2dlidWXlVUVimQC+CiZmFta2qAVOru6ePn4BQSChEdGx8Qg0iSApqPUZqDn5xaUV1bXHTa1ZBZSZQ2V5eWJV2ZkFdqPjIKZdlMbGgyvMyG4POhlv5Aop1mFIugYnEEvDDscsrlCiVypUapk6uk7m1TmVKAUqh87AB2ArZOnvApjCZAqwg1DZcGQpa+WFrDZIkAonZ7dGpBpY864q4EokNEkPJ5FIYMylU7J2FkAybsmZibmLaF81bwwVbVG7fYY9JSnGXfE3YnNUlnMoFal0mnDFVlbWA8x6tBVQ1Q7wmuEhREW0XWiUnM72vHXQm3F1SuzZPI1Coegr9Ir+3XTNA00O8laRhGbZHbNHJeN2i7JuVp+6nCRlV7uvrZFW-ItskuncvGysC6O1y1ihtHW2nbHN2VOhXpjuUPtiTO-V6+v6swPDoqj8Pjs2T4V1q3iueShfSh0p+WNNdnMRZzJiMqfap2PI0wdDw5P8TxhU0oxrS9pzjW8E0XGVHVTZ120-DcqjsekumeQlikA4EZjsepnAhI1T35c9IIASVkZQGD8FwMlnTFUCKDoCg9Gl0LED5swKTJkNJIo8koX4aRpVi7G-cTKjwoMjjmEBiJ5MdyIgoVqNo+jGIORsWLYjiuJ4qo+IEtAhMoCoCzyLsym9CpZOHSTQIjCcqJoujMAYm9mNYikDLsbiql4-jV3bcyuypb0xBpPssy1f4A3w+wuUUhYwzAqtzXQDSPK8pj5189josMoLjJCl8UKKSgCS3aLvjKD4-QS4tgINVKSPSlyKPU9ytO8gr9OKgKjJM0LXSqyKylYrpbO-BzgJDdrlLI8Dqx6zTPO0m070K-zAuC0zTiqzI-wqHIGU1KoqnmgiyyW0iMtc9bcq23TdqG-aysO8zMx6Xot1eP8xBu+wQqUh6urUzwcr6-KdsGzjhtK0aKsE4SPSKGk3mKAo6UzEGjmPe7OrPKHst6zb+vhvyPpG8rFSOyhhn-XHPizK4CYKPJnNJtboYpvKdNgsyEZKg6xpFjcxI+VUqgqMTOaItKK1UvnyY2wXtpOd7Ec+lGGfM98fizN4PnY+KDyS2YFPBknVaykAYcpuHtdFpHxdRszhKGPJvi-Ooim7TmwWJlXVodp3Nbet29fptdzM4332JyWq6U5lLbbDzKL0j17hb0mndbp762MzIZSg+Zn9x1IcOQ9Hn7ZzgW858mPi4lguvkI7iVU-KbmWa2uZkpBvw6bjWW4Gwuxa+jvCus-7MhpQiZMHoDh7uzOVLHtyJ6p13p-d2fPZY723jyFVsiqMTV8tuTRq3lbs93l798loqi+RuOwo6Mpum9LmK92IDzvsOYoo9n7PVhkLVuh9Y7fWEuhQY9JjJ-0DhbGu69QTc1DtvSB-M94u3fntduJ9fK0hKF+XM2R+jZAJhUCBT0CGvyIQXD+M99bxzYn2WyV96p2CuvQm2ys8FMPViwmBU92FH04T-DceQeG2SxhXACa8rZdkYd1Zh0CtbENpl-EuIkBFfi-F8E6Cs1FyT-posmjtm5vzYSQgxc8Oh-hqJ8Yogcij5noW1R+j0tHiJ0dHOBpCDaIKxtkPi1lr4YQwYlKxi1-GQzVnYwhkjqbSPgS4tCJQr6xP-iAzB6jN4iKfmItJEjdGOP0R7A2HR3jiXeEgyJdDLHDn6DY1JucHE6w4d-NGnQaHdAERcKK9CibJN5hHexrC+kyIGZLWkWZuJY1xrVAmWYukzPSdU+Z2SyHcLqGIdi34vwqk2UrDqWcKk9LmW3ZxZDhK9EIv0cofFPzVwScOKJ2zx5VJCVksJ8dEEKJxH-D07oinfI5DQv5L9gn532cCuRJtehX28T0TimyM5lICbYu5GSD5AsefUkSDJBgqiCpjey7TYV+LxSknZAKkUPLqSCygkThg0lKD8LcXyWozCvvCqBzsiV6M-uysKiDfjlGXnk70bTQGwtKdc0RgTKmItgSSqVgzGoNVOq8di106VCrBoy6Z-ytVSKcbqr2TMSiVHfA1ZePxNmTItY3BFYq9lsuPmS2kbw-6FGvrjeJgq0C9BFdon1gLbX+o5TFOkS8Xg0n6OGoekarnLXxd02Z4qamSoTWFR4dR0KZh5YFUoBMTnRqCbG1loTSXx0eHxSoNCvziUDkq4pckvx1s1Q27V8bZGCQ6Cc45vx8zZmzDW3FarykasJb6ptdqWKtqzKg9UQkBymsjQyhdubmXWsySOxZBckGZmoZ8WyNakmep3qKqOjadXFsEqWzUGLeE0KXjW1VOamVWqHTa2pb6zKtu8WXQk7jfY1vNYewD3rn3DtA6OyWgwTpbnYriWDe7UBiA9Qhy1SHJ6ntQ+e3yzwgoUr7FzQReGgoDuXXG8j31HiaiXnjK6BG+wE3Qkx-NK7X1oYLkvK6abaSEjMXx4RRGvVPtI8Ss9bGLJSfdO+f8cq+MhymfJmNyGQNFpE94kSdJqjem8R6GhfH50AeIwp3pfrjOPACsnZOzxqjAwYweuzen60GbI0ZijLmuj7SEkmwsDH71ycffpxTEr+mGJ7svKjdHrJ8f-RDezcXHOrrAwXFU5sMZ8Winx+DvnYv+fi4WxLc92M1HfBhTFabVHKpmIMATuyWNBcMSUbxhWPjfEKATLGnWWUoZ6zklUjUKXugJCN7NWW-ODoC0p1jdWLK+y+DLDFX4RuyYq-gqruXhMUY6DFF1AUsL5mhRG1AaaTwAAUYCOA1SKesBbUKrM8-KwYD2O5nC+DmLsJzvy4xG7Z0iz3Xu2Pe9eVhX3oo-fxDSw65QngYskriDFt3M33Z81Dl7b2rwzk+xIb7kUUf-ZPujuyklvgBRitfEb0XlrQ+J9BBxiPxKU+qKjgHEhKTvO6LmT4Aq8diSe0T2HJOYLMW58jvn1OGaoS7BfWkP4rrVBG+VwnMPUlw9J9UhXvO-shxp7kNNORPhdopeLrB93CNs+lwb2XXPydI9N-zmnEg3gNZOVzQGGaHeEil-rh2hu5fzhN9FKn5uVcSAEa8bMNQShUmD1bE6YeOexnd0zT3selfx9fJ2MStkBEp77PbzPB29c54+8bj3PPC9m7R7774pQehA0kj2mFMxyjZ5l5zhHTfFet4B1UfIX4+7eN6DkVrvbhw5EH674fZP8-N9+97hPnQ3E9EK5uDPclPwr4j27kfG+x-b9fJPsFcsDXvnfNX4-rO69D9zxfinLfr8oUn90NUQ2rEy8ved2S8p+F4keeeX+W+yuN+Fk18pQS8hQ-4mMBMpQ4BkEkBn+BeMBxeKENI+QfYOIGEmQxkJqbWWQTub+q+H+6+0BceaOk+NQYaDUNC2YvGeGQkGBQoWBdBOBDBAOBBNCQBXQMUHoW4BMrE3BOWcy5IvsIOFc3wV8KUhy8iJyhEJ0GhzOnBteYY7OBKgmb0ch5QDUihKCKhBsjwf8zwH41kNC9GFBLEOmZS+heaXWSKxhChny5h305IFelIPwnw7aR+R4kOehLux6wGO0nhph3hyhvh8ilC3EhQzwCikhBO4R4eQGq2ZkMRwwcRnwCRjSvEWMbyXYkhr+mRS6hhHh+QJh+RwwPhG2aa-QXMPC4kv6nBmWVRBh7hPkeRZh8Rc8fhQU6ugwxi7wkhuuPRbh42BUAxBRFh8c5IpR7we4vQf8khVBMxkRORThdRXhjRQxZC5IJhYk5sxkHoBMf4OCj8rhux1WgcBxsRRxhRc8i4AUhEHoWuXwIwAAumMCAAAGZIBQBwCYBoCgBQBsC6AIDyCaDAk0BwCCAzChxKCYBpA4BhhhDKDmA6DwiYB0CCBhiZyAkuBsCkigBAlIkomeDmjomYnYkuC4myD4nolElhjmgjCAkQBYlQCQkYBwA0BkBYD2BRogAtA2D0Bik4KCBIBpABBGCgDICQQBDkkuBMBIAuDwhwCyDQkslkACmHBUk0mokpAMlYmeAACODASAsghJ6ghJpA8ISASQNABgCJ2gug+gRgDgdgfxSgcpTAyJAAokkDgNqegCAICQ6cSZ4PCNADoFCKAMoGwMgOYEYM8goOOgCYCScCaciaiZ7BaWGDaXaQ6WoDQM6eyZgHGegAAMo6BanaSJl1kplplIAZmoCGAnRDI9B9ADDlwKBdDnCfEYQfCDBfC5ncn-AqlIigAYmWnoA4BsDmAQlKDUmCDEkzCeR6CAm6n6nmCGkInGmImFmeDmkgCLmlm2n2l0CVnVkgCunukClel6AemGB+kBkgBBmhnhmRkgDRk1l1mAVKCtnJkqAdldmGBZk5kzl3gFm0noDaTXnWm3kVlOkeDAVhiNlymCzgUCmpnpnwk9kdBdD9n07fhDkjmFBjnfGTmZDTn-HclAA) it's not quite right! @giorgi-ghviniashvili any idea what might be missing there?

**Comment by sharlagelfand** [comment]
Just closing the loop on the issue with error bars not appearing with both row/column facets - they are there, just tiny! Related to #54 in terms of zooming in on the final view.

**Comment by giorgi-ghviniashvili** [comment]
Ok, so I managed to hack error bars for both: faceted and non-faceted views.

https://user-images.githubusercontent.com/6615532/119651664-4af4ca00-be36-11eb-9489-fcc648e472fb.mov

 * fixed "1px left" issue
 * last layer (from `layer` array) is animated always which eliminated "point moving up" issue that I showed in the meeting

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand  I will make it work for row + column facets..

**Comment by giorgi-ghviniashvili** [comment]
@jhofman @sharlagelfand it is not possible to hack a layer that has `mark = errorbar` with facets, so I am just drawing it with real facets and errorbars..

Only second layer which is not `errorbar`, and is `mark = point`, is animated.

![image](https://user-images.githubusercontent.com/6615532/119707714-85795980-be6c-11eb-8da6-bbe13b30b4fd.png)

But in this case, I see that error bars not correctly aligned..

Unfortunately the fix that I talked yesterday that I hacked all faceted layers only worked for row facets + errorbars, but did not work for column + row facets + errorbars..

**Comment by sharlagelfand** [comment]
As we talked about in our call, I'll look into manually calculating the error bars and passing via something like [rule](https://vega.github.io/vega-lite/docs/rule.html) rather than using mark "errorbar"

**Comment by sharlagelfand** [comment]
@giorgi-ghviniashvili [here](https://github.com/microsoft/datamations/blob/parse-ggplot2/sandbox/errorbar/errorbar_using_rule.json) is an example spec using `rule` instead of errorbar

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand  @jhofman  I fixed alignment issue in hacked faceted view: 

![image](https://user-images.githubusercontent.com/6615532/119970646-0c3f4b00-bfc1-11eb-9339-b5033f853d66.png)

**Comment by giorgi-ghviniashvili** [comment]
This means that if we only hack animated layer and just draw others , will work. Should I still work to fake `rule` spec?

**Comment by giorgi-ghviniashvili** [comment]
@jhofman  the height was not correctly generating, from -4.7px to 305px, height should have been 309.7px, I was only using 305px for height (assuming that min would be 0..). 

I think it will work generally going forward..

**Comment by sharlagelfand** [comment]
@giorgi-ghviniashvili will this approach work with different sizes? The size of the whole widget can change and each row can be different sizes depending on the number of variables in the row facets

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand , yes I think it will work, we can test bunch of specs if you have.

**Comment by sharlagelfand** [comment]
@giorgi-ghviniashvili I will remove my logic for rule instead of errorbar, update with the latest code and push the app so we can test scenarios through that

**Comment by sharlagelfand** [comment]
@giorgi-ghviniashvili I noticed a couple issues with the errorbars for [this spec](https://github.com/microsoft/datamations/blob/parse-ggplot2/sandbox/errorbar/dual_legend_missing_last_frame.json). There is two legends, one for the error bars and one for the points, and the last frame (zoom) does not get animated. When you go to it, it is empty - so maybe not being rendered correctly? Thanks!


https://user-images.githubusercontent.com/15895337/120003559-dd66ac00-bfa3-11eb-9a5b-e235dce34777.mov

**Comment by sharlagelfand** [comment]
Latest version of the app is [here](https://sharlagelfand.shinyapps.io/datamations/), it seems like the errorbar logic fix works because it is not actually hardcoded as e.g. 305px but rather uses [a dynamic value](https://github.com/microsoft/datamations/commit/9caf8bb89a1994abbea4b39fe2d8488570e202f6#diff-49eb26faa2dccb4ecde39ad326e5b1801995e9287b0742c6ff3f665393a4bd33R155)

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand  

* Two legends fixed with css:

![image](https://user-images.githubusercontent.com/6615532/120078270-bbfae280-c0bf-11eb-989c-93f58998a491.png)


* about last frame, the domain is NA here:

![image](https://user-images.githubusercontent.com/6615532/120078183-3414d880-c0bf-11eb-9176-f455099625f3.png)

As soon as you fix "NA" in domain, it will be fixed. 

----
Height was not supposed to be hardcoded..

**Comment by sharlagelfand** [comment]
Thanks @giorgi-ghviniashvili, my bad on NAs in domain! Fixed now, and the legends look good:


https://user-images.githubusercontent.com/15895337/120202068-2319b380-c1f4-11eb-82cf-88bdfd30cf2c.mov



re: height hardcoded, this comment made me think it was - but glad to see it's not!

> @jhofman the height was not correctly generating, from -4.7px to 305px, height should have been 309.7px, I was only using 305px for height (assuming that min would be 0..).
> 
> I think it will work generally going forward..

**Comment by jhofman** [comment]
small note on the error bar sequence: right now it looks like the following happens: we're zoomed out, error bars show up, then they disappear as we zoom in, then they reappear.

i realize this is due to the fact that gemini doesn't handle the error bars and we have to fake them, but am wondering if we can do something a bit different so they don't disappear and reappear.

option 1 would be to wait until zoomed to show the error bars, or just fade in the error bars while the zooming in happens?

option 2 would be to somehow fake the animation of them.

option 2 sounds hard. maybe we go with option 1 if that's the case?

**Comment by giorgi-ghviniashvili** [comment]
@jhofman yes, I know it and this is because we are faking it. 

 I am just clearing `div` element where the error bars are mounted, setting opacity to 0 and then fading opacity in (transition). I also have some delay before transition. It fades in just when zooming happens (this means that transition happens concurrently). 

Unfortunately I can't do anything different for this, because technically it needs to be deleted and then re-drawn. Otherwise it will not work.

So I think I am doing Option 1 right now. 

Also here is the video with delay = 0:

https://user-images.githubusercontent.com/6615532/121074865-7c31aa80-c7e5-11eb-80d9-6f9eb44fb141.mov

Maybe this is a bit better, let me know

-----
About option 2, it sounds hard, but also don't get how it should work, we should have another gemini animation under the main animation?

**Comment by sharlagelfand** [comment]
Looks like there's still an issue with errorbars when there's multiple row facets - I thought we already addressed this but seems like it may have popped up again! For [this spec](https://github.com/microsoft/datamations/blob/parse-ggplot2/sandbox/errorbar/row_facet_x_errorbars_off.json):

<img width="888" alt="Screen Shot 2021-06-08 at 4 14 23 PM" src="https://user-images.githubusercontent.com/15895337/121251215-9f576b00-c874-11eb-83a4-b1c2bb430228.png">
<img width="882" alt="Screen Shot 2021-06-08 at 4 14 31 PM" src="https://user-images.githubusercontent.com/15895337/121251224-a0889800-c874-11eb-8977-b65430185e2d.png">

**Comment by sharlagelfand** [comment]
Oh thanks @giorgi-ghviniashvili, just saw this commit! github doesn't seem to notify me of those :) Looks good now.
